name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        run: |
          chmod +x gradlew
          ./gradlew -v

      - name: Run build and test command
        run: |
          ./gradlew build

      - name: Run static analysis
        run: ./gradlew detekt

      # Uploads results to GitHub repository using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: build/reports/detekt.sarif
          checkout_path: build/reports/