name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        run: ./gradlew -v

      - name: Run build command
        run: |
          chmod +X gradlew
          ./gradlew build
